"""empty message

Revision ID: 1d35d7751694
Revises: None
Create Date: 2014-12-18 21:17:36.797462

"""

# revision identifiers, used by Alembic.
revision = '1d35d7751694'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
