"""Initial database.

Revision ID: 3f8599f1ba77
Revises: None
Create Date: 2014-12-18 21:47:50.840534

"""

# revision identifiers, used by Alembic.
revision = '3f8599f1ba77'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'logfiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'hosts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('host', sa.String(), nullable=False),
        sa.Column('port', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('host', 'port')
    )
    op.create_table(
        'processes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pid', sa.Integer(), nullable=True),
        sa.Column('spec', postgresql.JSON(), nullable=False),
        sa.Column('host_id', sa.Integer(), nullable=True),
        sa.Column('logfile_id', sa.Integer(), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('state', sa.Enum(
            'init', 'setup', 'running', 'failed', 'success', name='proc_state'
        ), nullable=True),
        sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
        sa.ForeignKeyConstraint(['logfile_id'], ['logfiles.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processes')
    op.drop_table('hosts')
    op.drop_table('logfiles')
    ### end Alembic commands ###
