"""empty message

Revision ID: 5665b5e38768
Revises: 3f8599f1ba77
Create Date: 2015-01-23 11:17:17.040830

"""

# revision identifiers, used by Alembic.
revision = '5665b5e38768'
down_revision = '3f8599f1ba77'

from alembic import op
import sqlalchemy as sa

from datetime import datetime


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logfiles', sa.Column('added_time', sa.DateTime(),
                                        # We let the old values be
                                        # empty as we'll probably just
                                        # drop them.
                                        nullable=True,
                                        default=datetime.now()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logfiles', 'added_time')
    ### end Alembic commands ###
